import QtQuick
import QtQuick.Layouts
import qs.services
import qs.modules.common
import qs.modules.common.widgets
import Quickshell
import Quickshell.Io

ContentPage {
    id: page
    forceWidth: true

    property var monitors: []
    property bool vrrOn: false
    // Tracks pending per-monitor overrides so persistDisplay() uses the new values
    // even before page.monitors refreshes (600ms delay after hyprctl eval).
    property var monitorPending: ({})
    // Both monitors and VRR must load before we can seed display.lua correctly.
    property bool monitorsLoaded: false
    property bool vrrLoaded: false
    property bool seeded: false

    function refresh() { monProc.running = true; vrrProc.running = true; }
    Component.onCompleted: refresh()

    function trySeed() {
        if (!seeded && monitorsLoaded && vrrLoaded && monitors.length > 0) {
            seeded = true;
        }
    }

    Process { // live monitor list (includes HDMI/external when connected)
        id: monProc
        command: ["hyprctl", "monitors", "-j"]
        stdout: StdioCollector { onStreamFinished: {
            try { page.monitors = JSON.parse(text); } catch (e) { page.monitors = []; }
            page.monitorsLoaded = true;
            page.trySeed();
        }}
    }
    Process {
        id: vrrProc
        command: ["hyprctl", "getoption", "misc:vrr", "-j"]
        stdout: StdioCollector { onStreamFinished: {
            try { page.vrrOn = (JSON.parse(text).int ?? 0) !== 0; } catch (e) {}
            page.vrrLoaded = true;
            page.trySeed();
        }}
    }
    // Writes display overrides to custom/display.lua so they survive hyprctl reload.
    Process { id: writeDisplayProc }
    Timer { id: reapplyRead; interval: 600; onTriggered: page.refresh() }

    function applyMonitor(m, opts) {
        const mode = opts.mode ?? `${m.width}x${m.height}@${m.refreshRate.toFixed(2)}`;
        const scale = opts.scale ?? m.scale;
        const transform = opts.transform ?? m.transform;
        Quickshell.execDetached(["hyprctl", "eval",
            `hl.monitor({output="${m.name}", mode="${mode}", position="auto", scale=${scale}, transform=${transform}})`]);
        // Merge opts into pending so persistDisplay() sees the new values immediately.
        const prev = monitorPending[m.name] || {
            mode: `${m.width}x${m.height}@${m.refreshRate.toFixed(2)}`,
            scale: m.scale, transform: m.transform
        };
        monitorPending[m.name] = {
            mode: opts.mode ?? prev.mode,
            scale: opts.scale ?? prev.scale,
            transform: opts.transform ?? prev.transform
        };
        page.monitorPendingChanged();
        persistDisplay();
        reapplyRead.restart();
    }
    function setVrr(on) {
        Quickshell.execDetached(["hyprctl", "eval", `hl.config({misc = {vrr = ${on ? 1 : 0}}})`]);
        page.vrrOn = on;
        persistDisplay();
    }
    function persistDisplay() {
        const lines = ["-- Auto-generated by Settings > Display. Delete this file to reset to defaults."];
        for (let i = 0; i < page.monitors.length; i++) {
            const m = page.monitors[i];
            const p = monitorPending[m.name];
            const mode = p ? p.mode : `${m.width}x${m.height}@${m.refreshRate.toFixed(2)}`;
            const scale = p ? p.scale : m.scale;
            const transform = p ? p.transform : m.transform;
            lines.push(`hl.monitor({output = "${m.name}", mode = "${mode}", position = "auto", scale = ${scale}, transform = ${transform}})`);
        }
        lines.push(`hl.config({misc = {vrr = ${page.vrrOn ? 1 : 0}}})`);
        const content = lines.join("\n") + "\n";
        writeDisplayProc.command = ["python3", "-c",
            "import sys,os; open(os.path.expanduser(sys.argv[1]),'w').write(sys.argv[2])",
            "~/.config/hypr/custom/display.lua", content];
        writeDisplayProc.running = true;
    }

    // Brightness (per connected screen)
    ContentSection {
        icon: "brightness_6"
        title: Translation.tr("Brightness")
        Repeater {
            model: Quickshell.screens
            delegate: RowLayout {
                required property var modelData
                readonly property var bm: Brightness.getMonitorForScreen(modelData)
                Layout.fillWidth: true
                spacing: 10
                visible: bm !== null
                MaterialSymbol { text: "brightness_low"; iconSize: Appearance.font.pixelSize.larger; color: Appearance.colors.colOnSurfaceVariant }
                StyledSlider {
                    Layout.fillWidth: true
                    from: 0.01; to: 1
                    value: parent.bm?.brightness ?? 1
                    onMoved: if (parent.bm) parent.bm.setBrightness(value)
                }
                StyledText {
                    Layout.minimumWidth: 38; horizontalAlignment: Text.AlignRight
                    color: Appearance.colors.colOnSurface
                    text: `${Math.round((parent.bm?.brightness ?? 0) * 100)}%`
                }
            }
        }
    }

    // Adaptive sync (global). VRR capability isn't reliably exposed (kernel
    // vrr_capable is often absent), so we gate on refresh rate: only offer the toggle
    // when a connected monitor runs above 60Hz, where VRR is actually meaningful.
    // (A plain 60Hz panel gets nothing from it and it can cause flicker.)
    readonly property bool anyHighRefresh: page.monitors.some(m => (m.refreshRate ?? 0) > 61)
    ContentSection {
        visible: page.anyHighRefresh
        icon: "monitor_heart"
        title: Translation.tr("Adaptive sync (VRR)")
        ConfigSwitch {
            buttonIcon: "sync"
            text: Translation.tr("Variable refresh rate")
            checked: page.vrrOn
            onCheckedChanged: if (checked !== page.vrrOn) page.setVrr(checked)
            StyledToolTip { text: Translation.tr("Matches refresh to content. On some laptop panels this can cause a 60Hz feel/flicker — turn off for constant max refresh.") }
        }
    }

    // Per-monitor controls
    Repeater {
        model: ScriptModel { values: page.monitors }
        delegate: ContentSection {
            required property var modelData
            readonly property var m: modelData
            icon: "desktop_windows"
            title: m.name + (m.model && m.model !== "" ? `  ·  ${m.model}` : "")

            // Resolution + refresh
            ContentSubsectionLabel { text: Translation.tr("Resolution & refresh") }
            ConfigSelectionArray {
                currentValue: `${m.width}x${m.height}@${m.refreshRate.toFixed(2)}`
                onSelected: newValue => page.applyMonitor(m, { mode: newValue })
                options: (m.availableModes ?? []).map(s => {
                    const clean = s.replace("Hz", "");
                    const at = clean.split("@");
                    const res = at[0], rate = at[1] ?? "60";
                    return {
                        displayName: `${res.replace("x", "×")}  ${Math.round(parseFloat(rate))}Hz`,
                        value: `${res}@${rate}`
                    };
                })
            }

            // Scale
            ContentSubsectionLabel { text: Translation.tr("Scale") }
            ConfigSelectionArray {
                currentValue: m.scale
                onSelected: newValue => page.applyMonitor(m, { scale: newValue })
                options: [
                    { displayName: "100%", value: 1.0 },
                    { displayName: "125%", value: 1.25 },
                    { displayName: "150%", value: 1.5 },
                    { displayName: "160%", value: 1.6 },
                    { displayName: "180%", value: 1.8 },
                    { displayName: "200%", value: 2.0 }
                ]
            }

            // Rotation / transform
            ContentSubsectionLabel { text: Translation.tr("Rotation") }
            ConfigSelectionArray {
                currentValue: m.transform
                onSelected: newValue => page.applyMonitor(m, { transform: newValue })
                options: [
                    { displayName: Translation.tr("Normal"), icon: "screen_rotation_up", value: 0 },
                    { displayName: "90°", icon: "screen_rotation", value: 1 },
                    { displayName: "180°", icon: "screen_rotation", value: 2 },
                    { displayName: "270°", icon: "screen_rotation", value: 3 }
                ]
            }

            StyledText {
                Layout.topMargin: 2
                font.pixelSize: Appearance.font.pixelSize.smaller
                color: Appearance.colors.colSubtext
                text: {
                    const parts = [`${m.width}×${m.height} @ ${m.refreshRate.toFixed(0)}Hz`, `scale ${m.scale}`];
                    if (m.make) parts.push(m.make);
                    return parts.join("  ·  ");
                }
            }
        }
    }

    property int screenTimeDays: 1

    function fmtDuration(sec) {
        sec = Math.round(sec)
        if (sec <= 0) return "—"
        const h = Math.floor(sec / 3600), m = Math.floor((sec % 3600) / 60)
        if (h > 0) return `${h}h ${m}m`
        if (m > 0) return `${m}m`
        return `${sec}s`
    }

    function computeScreenTime() {
        const now = Math.floor(Date.now() / 1000)
        const cutoff = page.screenTimeDays >= 9999 ? 0 : now - page.screenTimeDays * 86400
        const samples = Battery.batteryHistory.filter(s => s[0] >= cutoff)
        const appSecs = {}
        for (let i = 1; i < samples.length; i++) {
            const s = samples[i], prev = samples[i - 1]
            const dur = s[0] - prev[0]
            if (dur <= 0 || dur > 5400) continue
            if (s.length < 4 || typeof s[3] !== "string" || s[3] === "") continue
            const seen = new Set(s[3].split(",").map(p => p.split(":")[0]?.trim()).filter(Boolean))
            for (const name of seen)
                appSecs[name] = (appSecs[name] || 0) + dur
        }
        return Object.entries(appSecs)
            .map(([name, secs]) => ({ name, secs }))
            .sort((a, b) => b.secs - a.secs)
            .slice(0, 12)
    }

    ContentSection {
        id: screenTimeSection
        icon: "hourglass_empty"
        title: Translation.tr("Screen time")

        property var _items: page.computeScreenTime()
        property var _total: _items.reduce((a, x) => a + x.secs, 0)

        RowLayout {
            spacing: 4
            Repeater {
                model: [
                    { label: "Today",   d: 1 },
                    { label: "7 Days",  d: 7 },
                    { label: "30 Days", d: 30 },
                    { label: "All",     d: 9999 },
                ]
                delegate: RippleButton {
                    required property var modelData
                    buttonRadius: Appearance.rounding.small
                    toggled: page.screenTimeDays === modelData.d
                    implicitWidth: 70; implicitHeight: 30
                    downAction: () => { page.screenTimeDays = modelData.d }
                    contentItem: StyledText {
                        anchors.centerIn: parent
                        text: modelData.label
                        font.pixelSize: Appearance.font.pixelSize.small
                        color: Appearance.colors.colOnSurface
                    }
                }
            }
        }

        StyledText {
            visible: screenTimeSection._items.length === 0
            font.pixelSize: Appearance.font.pixelSize.small
            color: Appearance.colors.colSubtext
            text: "No screen time data in this range."
        }

        Repeater {
            model: screenTimeSection._items
            delegate: ColumnLayout {
                required property var modelData
                required property int index
                Layout.fillWidth: true
                spacing: 4

                RowLayout {
                    Layout.fillWidth: true
                    spacing: 8

                    StyledText {
                        Layout.preferredWidth: 18
                        horizontalAlignment: Text.AlignRight
                        text: `${index + 1}`
                        font.pixelSize: Appearance.font.pixelSize.smaller
                        color: Appearance.colors.colSubtext
                        opacity: 0.5
                    }

                    StyledText {
                        Layout.fillWidth: true
                        elide: Text.ElideRight
                        text: modelData.name
                        font.pixelSize: Appearance.font.pixelSize.small
                        font.weight: Font.Medium
                        color: Appearance.colors.colOnSurface
                    }

                    StyledText {
                        font.pixelSize: Appearance.font.pixelSize.smaller
                        color: Appearance.colors.colSubtext
                        opacity: 0.7
                        text: screenTimeSection._total > 0
                            ? `${Math.round(modelData.secs / screenTimeSection._total * 100)}%`
                            : ""
                    }

                    StyledText {
                        Layout.preferredWidth: 60
                        horizontalAlignment: Text.AlignRight
                        font.pixelSize: Appearance.font.pixelSize.small
                        font.weight: Font.Medium
                        color: Appearance.colors.colOnSurface
                        text: page.fmtDuration(modelData.secs)
                    }
                }

                StyledProgressBar {
                    Layout.fillWidth: true
                    value: screenTimeSection._items.length > 0
                        ? modelData.secs / screenTimeSection._items[0].secs : 0
                    highlightColor: index === 0 ? Appearance.colors.colPrimary
                        : index <= 2 ? Appearance.colors.colSecondary
                        : Appearance.colors.colTertiary
                }
            }
        }

        StyledText {
            visible: screenTimeSection._items.length > 0
            font.pixelSize: Appearance.font.pixelSize.smaller
            color: Appearance.colors.colSubtext
            opacity: 0.6
            text: `Total: ${page.fmtDuration(screenTimeSection._total)}  ·  ${screenTimeSection._items.length} apps`
        }
    }
}
