#!/usr/bin/env bash
# Persists current Hyprland monitor state to monitors.lua so settings survive reloads.
# Called by Settings > Display ~700ms after any monitor change (gives hyprctl eval time to settle).

OUT="$HOME/.config/hypr/monitors.lua"

{
    echo "-- Auto-generated by Settings > Display. Edit there, not here."
    hyprctl monitors -j | jq -r '.[] | [.name, .width, .height, .refreshRate, .scale, .transform] | @tsv' \
    | while IFS=$'\t' read -r name width height rate scale transform; do
        mode=$(printf "%dx%d@%.2f" "$width" "$height" "$rate")
        printf 'hl.monitor({output="%s", mode="%s", position="auto", scale=%s, transform=%s})\n' \
               "$name" "$mode" "$scale" "$transform"
    done
} > "$OUT"
